const $=id=>document.getElementById(id);
let socket=null, room=null;
function log(m){ const el=$('log'); el.textContent += m+"\n"; el.scrollTop=el.scrollHeight; }
function renderScores(scores){ const box=$('scores'); box.innerHTML=''; Object.values(scores).sort((a,b)=>b.score-a.score).slice(0,10).forEach((p,i)=>{ const d=document.createElement('div'); d.className='line'; d.innerHTML=`<div>${i+1}. <b>${p.name}</b></div><div>${p.score} pts</div>`; box.appendChild(d); }); }
function connect(){ const url=$('ws').value.trim(); room=$('room').value.trim().toUpperCase(); if(!url||!room){ alert('Serveur + salle'); return; } socket=io(url,{transports:['websocket']}); socket.on('connect',()=>log('✅ Connecté')); socket.on('disconnect',()=>log('❌ Déconnecté')); socket.on('room-info', i=>renderScores(i.scores||{})); socket.on('player-joined', p=>log('👤 '+p.name+' a rejoint')); socket.on('answer-received', p=>log('✍️ '+p.name+' → '+p.answer)); socket.on('scores', s=>renderScores(s)); }
$('connect').onclick=connect;
$('start').onclick=()=>{ const type=$('qType').value; const q={room, type, text:$('qText').value.trim(), image:$('qImg').value.trim(), video:$('qVid').value.trim(), choices:type==='mcq'?[ $('cA').value,$('cB').value,$('cC').value,$('cD').value ]:[], answer:$('qAns').value.trim(), points:parseInt($('qPts').value||'10',10), duration:parseInt($('qDur').value||'30',10), allowChange:true}; if(!q.text||!q.answer){ alert('Texte + bonne réponse'); return; } socket.emit('start-question', q); log('▶️ Question envoyée'); };
$('reveal').onclick=()=>{ socket.emit('reveal',{room}); log('🎬 Révélé'); };
$('loadRound').onclick=()=>{ const round=$('roundName').value.trim(); if(!round){ alert('Nom de manche'); return; } socket.emit('host-join',{room}); socket.emit('start-from-server',{room, round}); log('📂 Demande manche \"'+round+'\"'); };
$('nextServer').onclick=()=>{ socket.emit('next-from-server',{room}); log('➡️ Question suivante (serveur)'); };
$('qrBtn').onclick=async()=>{ const base=$('playerUrl').value.trim().replace(/\/+$/,''); if(!base){ alert('URL Player'); return; } const url=base+'/?code='+encodeURIComponent(($('room').value||'').trim().toUpperCase()); await QRCode.toCanvas($('qrCanvas'), url, {width:256}); log('🔗 QR: '+url); };
